### ISSUE TITLE
who is the owner and what is the project for???????????

### ISSUE THREAD

**Issue by pristineliving** [of1201/Retail-Credit-Modeling#1]
please elaborate.

**Comment by of1201** [comment]
Sorry I added the wrong person you two have the same Chinese name lol

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pristineliving** [comment]
> Sorry I added the wrong person you two have the same Chinese name lol Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)

QAQ it's ok! Very interesting project though! May you all have great progress in 2021!
